---

- dynamic_defaults:
    hostvars: '{{ hostvars[inventory_hostname] }}'
    defaults: '{{ mariadb_dynamic_defaults }}'
    must_match: yes
  tags: [mariadb-client, always]

- block:
    - include_tasks: setup-{{ ansible_pkg_mgr }}.yml

    - name: Install MariaDB client packages
      package:
        name: '{{ mariadb_client_packages }}'
        state: present
  become: yes
  tags: [mariadb-client, packages]
